"""
📌 Problem: Pascal's Triangle
-----------------------------
Given an integer `numRows`, return the first `numRows` of Pascal's triangle.

In Pascal's Triangle:
- The first row is [1]
- Each subsequent row is built by summing adjacent elements from the previous row,
  with 1 added to the beginning and end.

📥 Input Examples:
Example 1:
    Input: numRows = 5
    Output: [
        [1],
        [1, 1],
        [1, 2, 1],
        [1, 3, 3, 1],
        [1, 4, 6, 4, 1]
    ]

Example 2:
    Input: numRows = 1
    Output: [[1]]

-----------------------------
🧠 Solution Strategy:

We start with the first two rows:
- Row 1 → [1]
- Row 2 → [1, 1]

From the 3rd row onwards:
- Create a new row beginning and ending with 1
- The inner values are generated by summing adjacent values from the previous row

For example, to generate the 4th row:
- Previous row = [1, 2, 1]
- New row = [1, (1+2), (2+1), 1] → [1, 3, 3, 1]

Repeat until we generate `numRows` rows.

-----------------------------
⏱ Time and Space Complexity:

- Time Complexity: O(numRows²)
    - Each row has at most `numRows` elements; all rows together ≈ n(n+1)/2 operations
- Space Complexity: O(numRows²)
    - We're storing all rows of the triangle in memory

"""

from typing import List

class Solution:
    def generate(self, numRows: int) -> List[List[int]]:
        """
        Generates Pascal's Triangle up to the given number of rows.

        :param numRows: int - number of rows to generate
        :return: List[List[int]] - Pascal's triangle as a list of lists
        """
        if numRows == 1:
            return [[1]]
        elif numRows == 2:
            return [[1], [1, 1]]
        else:
            triangle = [[1], [1, 1]]
            for i in range(numRows - 2):
                new_row = [1]
                last_row = triangle[-1]
                for j in range(len(last_row) - 1):
                    new_row.append(last_row[j] + last_row[j + 1])
                new_row.append(1)
                triangle.append(new_row)
            return triangle


# 🔧 Test Case
if __name__ == "__main__":
    numRows = 5

    print(f"Pascal's Triangle with {numRows} rows:")
    result = Solution().generate(numRows)
    for row in result:
        print(row)
